### ISSUE TITLE
Added new content type, but using this API returns everything

### ISSUE THREAD

**Issue by ps23Rick** [backdrop-contrib/headless#38]
Ok.. Not sure if this is just normal backdrop behavior or not.  If I create a new content type --navpage which has a title field, body and slug. I then create ONE new navpage based on this new content type.  When I visit : http://localhost/api/v2/node/navpage/1, I get the first post content. If I pull up the http://localhost/api/v2/node/navpage/2 page, I get the About page content, and when I pull up http://localhost/api/v2/node/navpage/3, I get my NEW NavPage content.

In Drupal and the few other CMS I've played with, if I do the same thing -- as far as I recall, when I create a new content type, things are typed so that the new content would be accessible by the URL http://localhost/api/v2/node/navpage/1 and not /3.. The first post and About posts would NOT be pulled up because they're different types (post, page, vs navpage).  Is this normal??  I can certainly work around it but it was unexpected.  Thx

**Comment by serundeputy** [comment]
@ps23Rick thanks for reporting this.

That is not the expected behaviour ... I'll have to find some time to look into it.

@robertgarrigos if you get a second can you check out if th e`v2` endpoints are not namespacing by `type`?

NOTE
---------

I have not tried to reproduce this yet.

**Comment by serundeputy** [comment]
I just had a peek at the code and neither the `v1 or `v2` namespace by `type` properly.

https://github.com/backdrop-contrib/headless/blob/1.x-1.x/headless.module#L107

They check that the site has exposed that `type` of content as an endpoint and then proceed to load the node regardless of `type` and serve the json output.

We could/should also check the that the loaded `$node->type == $type` before we serve the json.

Not sure what the json error should be in this case? 

  * we could just 404 
    * i.e. return minimal info
  * could possilby set 
    * `$json_error` to 'Type mismatch; connection refused'
 
@ps23Rick you up for creating a PR on this?

**Comment by ps23Rick** [comment]
Sure... Do you just need a more descriptive rundown on how to reproduce it?  I can tackle that a bit later this AM (its 5:30am local time where I'm at). Thanks for the quick replies guys!!

**Comment by serundeputy** [comment]
@ps23Rick  No. I understand how to reproduce it.

STR:
  * visit `/api/node/page/1`
    * see node page one json response :heavy_check_mark: 
  * visit `/api/node/page/2`
    * see about page `article` type json response :heavy_multiplication_x: 

We need a PR that changes the code in `headless_type` and `headless_type_v2` to check that the requested `$type` is the same as the `$node->type`.

`headless_type` function is here
  * https://github.com/backdrop-contrib/headless/blob/1.x-1.x/headless.module#L85

`headless_type_v2` is here
  * https://github.com/backdrop-contrib/headless/blob/1.x-1.x/headless.module#L100

If that makes sense to you and you are up for a PR that'd be great otherwise @robertgarrigos or I will get to it when time permits.

**Comment by ps23Rick** [comment]
Oh.. You want me to try changing the code?  Heck ya!  I'd like to give that a shot for sure!   I'll try it a bit later this morning and get back with you all to give you an update on whether it worked or not.  Thanks so much!!

**Comment by serundeputy** [comment]
> Oh.. You want me to try changing the code? 

  * yes! 

If you need help w/ git, github, or filing Pull Requests (PRs) let us know and we can help you through the process!

**Comment by ps23Rick** [comment]
I've got the code-pull thing down but will admit that I've not done any of the rest of it before so I'll probably need a little teaching on that when the time comes.  I just decided to do the code-pull just now and have done so.. I'll take a look and hopefully get back to you-all a little later.

**Comment by ps23Rick** [comment]
Hey @serundeputy... Ok. I've got the changes ready and tested.  They work great. I can see the different types of output (v1 vs v2), etc.  I get the respective 404 errors for mismatches as expected.  Now, for me comes the hard part.  This will be my first GitHub PR and whatever comes after.  Is there anything specific I should know, etc..?  I just want to ensure I don't mess something up.

**Comment by serundeputy** [comment]
fork this repo to your user (if you haven't already)
add your fork as a remote:

```bash
git remotes -v # list your remotes
git remote add ps23Rick REPLACE_WITH_ssh_git_url_of_your_fork
```

checkout a new branch on your local.

```bash
git checkout -b 38/scopeAPITypes
```

commit your changes to the new branch

```bash
git add headless.module
git commit -m "Issue #38: Scoping API endpoints to respect type params."
```
> assuming that is the only file you changed

push the changes up to your fork

```bash
git push ps23Rick 38/scopeAPITypes
```

go to your github fork in  browser and file a PR against the backdrop-contrib/headless module

Let me know if that makes sense.

**Comment by serundeputy** [comment]
@ps23Rick this looks great!

The code standards are complaining: https://travis-ci.org/github/backdrop-contrib/headless/builds/671799117?utm_source=github_status&utm_medium=notification

Do you have time to add a commit to your branch and push it up that addresses the standards?

Looks like it is just complaining about the comments not starting w/ capitials ending w/ full stops and now whitespace at the ends of lines.

If you don't have time just let us know.

thanks for this great PR!

**Comment by serundeputy** [comment]
Just as an fyi here are the coding standards: https://api.backdropcms.org/php-standards

you can check the standards locally by running:

```bash
vendor/bin/phpcs -n --standard=vendor/backdrop/coder/coder_sniffer/Backdrop --ignore="vendor/*,README.md" --extensions=install,module,php,inc,theme .
```

or wait for them to run in travis CI as they did in this case.

**Comment by ps23Rick** [comment]
No problem!  I'll tackle that shortly.  Thanks for the links to the standards.. Been there done that but never for PHP. lol.

**Comment by ps23Rick** [comment]
Ok.. Stupid question.. I had to install composer & phpcs and I installed the Drupal coding standards.  I was thinking of just doing a sym-link to create the above Backdrop vendor stuff but it looks more involved than that.  Is there an archive somewhere that I can just pull and use it or is it a roll-your-own sort of thing?  I just don't want to re-roll these if they're sitting around somewhere on GitHub or elsewhere.  Thanks!

**Comment by serundeputy** [comment]
the easiest/best thing to do is

```bash
cd BACKDROP_ROOT/modules/contrib/headless
composer install
```

that will grab all the testing dependencies from the `composer.json` file included in the `headless` repo.

I use [`lando/lando`](https://lando.dev) to manage having php, composer, node, dependencies etc, w/out cluttering up my local machine and be able to have diff php's on diff apps etc, etc. 

Here is the `.lando.yml` file i use to contribute to the various `backdrop-contrib` modules i work on:

```yml
# Backdrop recipe
name: backdrop-contrib

# Start with the default Backdrop recipe
recipe: backdrop

# Configure the Backdrop recipe
config:
  via: nginx
  php: '7.3'
  webroot: .
  backdrush: 1.x-1.x
  database: mariadb:10.3
  xdebug: true

services:
  appserver:
    run_as_me:
      - composer i
    run_as_root: 
      - ln -snf /usr/share/zoneinfo/America/New_York /etc/localtime

  node:
    type: node:10

tooling:
  drush:
    service: appserver
    cmd: drush --root=/app --uri=https://backdrop-contrib.lndo.site
  npm:
    service: node
    cmd: npm
  yarn:
    service: node
    cmd: yarn
  node:
    service: node
    cmd: node
  phpcs:
    service: appserver
    cmd:
      - "/app/vendor/bin/phpcs -n --report=full --standard=/app/vendor/backdrop/coder/coder_sniffer/Backdrop --ignore=vendor/*,README.md --extensions=install,module,php,inc,theme"
```

in the `tooling` section i've exposed `phpcs` with a command that runs `phpcs` against the `backdrop/coder` standards.

```bash
lando phpcs /path/to/headless/
```

If you end up on the `lando` path the first step would be `lando composer install`.
